[project]
name = "jupyter-to-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=0.201.1",
    "nbformat>=5.10.4",
]
